title: Nidhi Singh # your name (or website title) here
logo: "/images/Nidhi_Photo.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Exploring Neural Networks!
  <br><br>
  <a href="https://www.linkedin.com/in/nidhi9590/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
