title: Nidhi Singh # your name (or website title) here
logo: "Nidhi_Photo1.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  #Welcome to my portfolio! I mm Nidhi Singh, a passionate AI enthusiast dedicated to leveraging the power of data to solve real-world problems. With a strong foundation in computer science and hands-on experience in developing and deploying machine and deep learning models, I thrive on turning complex datasets into actionable insights.
  # <br>
  # Over the years, I have worked on a variety of projects that span Image and text classification, dynamic system control, sentiment analysis, text summarization, and portfolio optimization. My expertise in Python, PyTorch, and data Science, combined with my commitment to continuous learning, drives my ability to deliver innovative and impactful AI solutions.
  # <br>
  # I invite you to explore my portfolio to see how I have applied my skills in various domains and to learn more about my journey in the exciting field of Machine Learning. Let us connect and discuss how we can collaborate to push the boundaries of what is possible with AI!
  <br><br>
<a href="https://www.linkedin.com/in/nidhi9590/">View My LinkedIn Profile</a> 
  

